### ISSUE TITLE
NaN error

### ISSUE THREAD

**Issue by lynn2thicc** [Rurusachi/loghorizontrpg#3]
Whenever you roll anything from the sheet, the total will show up as a NaN error instead of the correct total.

**Comment by Rurusachi** [comment]
What version of Foundry are you using? The current release doesn't work for versions higher than Foundry v8. I know this issue happens on later versions of Foundry. 

I'm working on a version for Foundry v11 that should be ready soon (within 2 weeks I hope)

**Comment by Rurusachi** [comment]
I released a new version compatible with Foundry v11. It should fix this problem if you were on a newer version than v8
